name: Docs

env:
  PIXI_LOCKED: true

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.52.0
    steps:
      - run: apt-get update && apt-get install -y build-essential git curl jq
      - uses: actions/checkout@v5
      - run: pixi run -e docs deploy
