name: Docs

env:
  PIXI_LOCKED: true

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-pixi
      - run: pixi run -e docs deploy
