name: Publish to PyPi

env:
  PIXI_LOCKED: true

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-pixi
      - run: pixi run -e build deploy
