name: Publish to Test PyPi

env:
  PIXI_LOCKED: true

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      TWINE_REPOSITORY_URL: "https://test.pypi.org/simple/"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          run-install: false
      - run: pixi run -e build deploy
