name: Test


env:
  PIXI_LOCKED: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.52.0
    steps:
      - uses: actions/checkout@v5
      - run: apt-get update && apt-get install -y build-essential git curl jq
      - run: pixi run -e lint lint

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.52.0
    strategy:
      matrix:
        GDAL: [gdal38, gdal39, gdal310, gdal311]
        PYSTAC_STAC_VERSION_OVERRIDE: ["1.0.0", "1.1.0"]
    steps:
      - run: apt-get update && apt-get install -y build-essential git curl jq
      - uses: actions/checkout@v5
      - run: pixi run -e dev-$GDAL test
